[package]
name = "chip8"
version = "0.1.0"
edition = "2024"
readme = "CHIP-8 emulator."

[dependencies]
sdl2 = "0.38"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
clap = { version = "4.5", features = ["derive"] }
